<?php

/**
 * Implements hook_block_info().
 */

function rowo_drupal_module_block_info() {
  $blocks['anbieter_suche'] = array(
    'info' => t('Oekostromanbieter-Suche'),
  );
  return $blocks;
}  


/**
 * Implements hook_block_view().
 */

function rowo_drupal_module_block_view($delta = '') {
  if ($delta === 'anbieter_suche') {
    $block = array(
      'subject' => t('Warum wurde dein Anbieter nicht empfohlen?'),
      'content' => array(
        '#markup' => theme('anbietersuche'),
      ),
    );
    $block['content']['#attached']['css'] = array(drupal_get_path('module', 'rowo_drupal_module') . '/suchstyle.css',);
    $block['content']['#attached']['js'] = array(
      drupal_get_path('module', 'rowo_drupal_module') . '/search.js',
      'https://cdn.jsdelivr.net/npm/vue' => array('type' => 'external'),  
      'https://unpkg.com/lunr/lunr.js' => array('type' => 'external'),
    );
    return $block;
  }
}


/**
 * Implements hook_theme().
 */

function rowo_drupal_module_theme() {
  return array(
    'anbietersuche' => array(
      'template' => 'anbietersuche',
      'variables' => array(
        'data' => base_path() . drupal_get_path('module', 'rowo_drupal_module') . '/indexanddata.json',
        'criteria' => base_path() . drupal_get_path('module', 'rowo_drupal_module') . '/criteria.csv',
                     ), 
    )
  );
}
