<?php

/**
 * Implements hook_block_info().
 */

function rowo_drupal_module_block_info() {
  $blocks['anbieter_suche'] = array(
    'info' => t('Oekostromanbieter-Suche'),
  );
  return $blocks;
}  


/** 
 * Implements hook_block_configure().
 */

function rowo_drupal_module_block_configure($delta='') {
  $form = array();

  if ($delta === 'anbieter_suche') {
    $form['file'] = array(
      '#name' => 'data_file',
      '#type' => 'managed_file',
      '#title' => t('Anbieter-Daten'),
      '#description' => t('JSON-Datei mit den Anbieter-Daten hochladen.'),
      '#upload_location' => 'public://anbieter_daten/',
      '#upload_validators' => array(
        'file_validate_extensions' => array('json'),
      ),
    );
  }
  return $form;
}


/**
 * Implements hook_block_save()
 */
function rowo_drupal_module_block_save($delta = '', $edit = array()) {
  if ($delta === 'anbieter_suche') {
    $file= file_load($edit['file']);
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);
    $block = block_load('rowo_drupal_module', $delta);
    file_usage_add($file, 'rowo_drupal_module', 'block', $block->bid);
    variable_set('block_data_fid', $file->fid);
  }
}

function rowo_drupal_module_block_view($delta = '') {
  if ($delta === 'anbieter_suche') {
    $block = array(
      'subject' => t('Warum wurde dein Anbieter nicht empfohlen?'),
      'content' => array(
        '#markup' => theme('anbietersuche'),
      ),
    );
    $block['content']['#attached']['css'] = array(drupal_get_path('module', 'rowo_drupal_module') . '/suchstyle.css',);
    $block['content']['#attached']['js'] = array(
      drupal_get_path('module', 'rowo_drupal_module') . '/search.js',
      'https://cdn.jsdelivr.net/npm/vue' => array('type' => 'external'),  
      'https://unpkg.com/lunr/lunr.js' => array('type' => 'external'),
    );
    return $block;
  }
}

function rowo_drupal_module_theme() {
  return array(
    'anbietersuche' => array(
      'template' => 'anbietersuche' 
    )
  );
}
